# Generated by Django 5.2.17 on 2026-08-15 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliefAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('PER_PERSON', 'Per affected person'), ('UNINHABITABLE', 'Property uninhabitable'), ('IMMEDIATE_RELIEF', 'Immediate relief required')], max_length=30, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_per_unit', models.BooleanField(default=False, help_text='If true, multiply by the count (e.g. people affected).')),
                ('max_amount', models.DecimalField(decimal_places=2, default=0, help_text='Ceiling for per-unit allowances. 0 means no ceiling.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'relief allowance',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ReliefRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_field', models.CharField(choices=[('structural_damage', 'Structural damage'), ('roof_damage', 'Roof damage'), ('wall_damage', 'Wall damage'), ('foundation_damage', 'Foundation damage'), ('electrical_damage', 'Electrical damage'), ('water_damage', 'Water damage'), ('household_damage', 'Household damage')], max_length=30, unique=True)),
                ('label', models.CharField(help_text="Wording shown on the citizen's breakdown.", max_length=120)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Full relief amount in rupees for damage graded DESTROYED.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'relief rule',
                'ordering': ['display_order', 'damage_field'],
            },
        ),
        migrations.CreateModel(
            name='CompensationClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=0, help_text='What the engine computed. Never overwritten by an adjustment.', max_digits=12)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='What the administrator authorised. May differ from the calculated amount.', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('CALCULATED', 'Calculated - awaiting review'), ('UNDER_REVIEW', 'Under administrator review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ADJUSTED', 'Adjusted by administrator')], db_index=True, default='CALCULATED', max_length=15)),
                ('adjustment_reason', models.TextField(blank=True, help_text='Mandatory justification when the approved amount differs.')),
                ('rules_snapshot', models.JSONField(blank=True, default=dict, help_text='The rule amounts in force at calculation time, so old claims stay auditable.')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_adjustments', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='compensation_claim', to='inspections.inspection')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_claim', to='reports.disasterreport')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='CompensationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('severity', models.CharField(blank=True, max_length=15)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('severity_factor', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compensation.compensationclaim')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
