# Generated by Django 5.2.17 on 2026-08-15 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(choices=[('roof_collapsed', 'Roof completely collapsed'), ('people_trapped', 'People trapped'), ('exposed_live_wires', 'Exposed live wires'), ('standing_water', 'Standing water'), ('road_blocked', 'Road blocked'), ('major_structural_damage', 'Major structural damage'), ('wall_damage', 'Wall damage'), ('medical_assistance_needed', 'Medical assistance needed'), ('people_affected', 'People affected (per person)')], max_length=40, unique=True)),
                ('label', models.CharField(help_text='Wording shown in the score breakdown.', max_length=120)),
                ('points', models.SmallIntegerField(help_text='Points added when this indicator applies.')),
                ('is_per_unit', models.BooleanField(default=False, help_text='If true, points are multiplied by the numeric value (e.g. people affected).')),
                ('max_points', models.PositiveSmallIntegerField(default=0, help_text='Ceiling for per-unit rules. 0 means no ceiling.')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'triage rule',
                'ordering': ['display_order', 'indicator'],
            },
        ),
        migrations.CreateModel(
            name='TriageThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10, unique=True)),
                ('minimum_score', models.PositiveSmallIntegerField()),
                ('maximum_score', models.PositiveSmallIntegerField(default=9999, help_text='Inclusive upper bound. Use a large number for the top band.')),
                ('response_target_hours', models.PositiveSmallIntegerField(default=72, help_text='Target time to first inspection, shown to officers and citizens.')),
                ('colour', models.CharField(default='#64748b', help_text='Hex colour for the UI badge.', max_length=7)),
            ],
            options={
                'verbose_name': 'triage threshold',
                'ordering': ['minimum_score'],
            },
        ),
        migrations.CreateModel(
            name='TriageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('breakdown', models.JSONField(default=list, help_text='Itemised list of rules that fired: [{indicator, label, points}, ...].')),
                ('response_target_hours', models.PositiveSmallIntegerField(default=72)),
                ('rules_version', models.CharField(blank=True, help_text='Timestamp of the newest rule used, so old results stay interpretable.', max_length=40)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('recalculated_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage_result', to='reports.disasterreport')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
