# Generated by Django 5.2.17 on 2026-08-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalInfrastructureSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('infrastructure_type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('SHELTER', 'Relief shelter'), ('POWER', 'Power infrastructure'), ('WATER', 'Water infrastructure'), ('BRIDGE', 'Bridge / arterial road'), ('COMMAND', 'Command facility')], max_length=20)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('impact_weight', models.PositiveSmallIntegerField(default=10, help_text='Risk contribution if this site is affected (1-15).')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['district', 'name'],
                'indexes': [models.Index(fields=['district', 'is_active'], name='triage_crit_distric_11f9a2_idx'), models.Index(fields=['infrastructure_type', 'is_active'], name='triage_crit_infrast_dc81b8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='infra_latitude_within_range'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='infra_longitude_within_range'), models.CheckConstraint(condition=models.Q(('impact_weight__gte', 1), ('impact_weight__lte', 15)), name='infra_impact_weight_range')],
            },
        ),
    ]
