# Generated by Django 5.2.17 on 2026-08-15 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted by officer'), ('IN_PROGRESS', 'Inspection in progress'), ('COMPLETED', 'Completed'), ('REASSIGNED', 'Reassigned to another officer'), ('CANCELLED', 'Cancelled')], db_index=True, default='ASSIGNED', max_length=15)),
                ('is_automatic', models.BooleanField(default=True, help_text='False when an administrator assigned this by hand.')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text="Straight-line distance from the officer's base to the incident.", max_digits=8, null=True)),
                ('selection_score', models.DecimalField(decimal_places=2, default=0, help_text='Higher is a better match.', max_digits=8)),
                ('selection_reason', models.TextField(blank=True, help_text='Plain-English explanation of why this officer was chosen.')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_by', models.DateTimeField(blank=True, help_text='Derived from the triage response target.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Null when the dispatch engine assigned automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(limit_choices_to={'role': 'FIELD_OFFICER'}, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='reports.disasterreport')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['officer', 'status'], name='dispatch_as_officer_2d2fa2_idx'), models.Index(fields=['status', '-assigned_at'], name='dispatch_as_status_75b503_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['ASSIGNED', 'ACCEPTED', 'IN_PROGRESS'])), fields=('report',), name='one_active_assignment_per_report')],
            },
        ),
    ]
