# Generated by Django 5.2.17 on 2026-08-15 04:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('CITIZEN', 'Citizen'), ('FIELD_OFFICER', 'Field Officer'), ('ADMIN', 'Administrator / Approver')], db_index=True, default='CITIZEN', help_text='Determines what this user is allowed to do across the platform.', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='Contact number used to reach the person about their case.', max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-15 digits, optional leading +).', regex='^\\+?[0-9]{7,15}$')])),
                ('address', models.TextField(blank=True, help_text='Postal address (citizens) or posting address (officers).')),
                ('district', models.CharField(blank=True, db_index=True, help_text='Administrative district. Used to match reports to nearby officers.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=40, unique=True)),
                ('zone', models.CharField(db_index=True, help_text="Operational zone this officer covers. Matched against a report's district.", max_length=100)),
                ('base_latitude', models.DecimalField(decimal_places=6, help_text="Latitude of the officer's duty station, used for distance ranking.", max_digits=9)),
                ('base_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text='Unavailable officers are skipped entirely by automatic dispatch.')),
                ('max_active_cases', models.PositiveSmallIntegerField(default=5, help_text='Workload ceiling. An officer at capacity is not auto-assigned more work.')),
                ('specialisation', models.CharField(blank=True, help_text="Optional expertise, e.g. 'structural', 'electrical'.", max_length=120)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text="Last time this officer's device pulled assignments for offline use.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officer', models.OneToOneField(limit_choices_to={'role': 'FIELD_OFFICER'}, on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'district'], name='accounts_us_role_0d99a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='officerprofile',
            constraint=models.CheckConstraint(condition=models.Q(('base_latitude__gte', -90), ('base_latitude__lte', 90)), name='officer_latitude_within_range'),
        ),
        migrations.AddConstraint(
            model_name='officerprofile',
            constraint=models.CheckConstraint(condition=models.Q(('base_longitude__gte', -180), ('base_longitude__lte', 180)), name='officer_longitude_within_range'),
        ),
    ]
