# Generated by Django 5.2.17 on 2026-08-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(blank=True, default='', help_text='How this account last signed in: password, google.com, or django.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, db_index=True, help_text='Firebase user id, set on first Firebase sign-in.', max_length=128, null=True, unique=True),
        ),
    ]
