# Generated by Django 5.2.17 on 2026-08-15 04:27

import django.db.models.deletion
import reports.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, editable=False, help_text='Human-friendly case number, e.g. RQN-2026-000042.', max_length=24, unique=True)),
                ('disaster_type', models.CharField(choices=[('FLOOD', 'Flood'), ('EARTHQUAKE', 'Earthquake'), ('CYCLONE', 'Cyclone / Storm'), ('LANDSLIDE', 'Landslide'), ('FIRE', 'Fire'), ('DROUGHT', 'Drought'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('damage_category', models.CharField(choices=[('RESIDENTIAL', 'Residential property'), ('COMMERCIAL', 'Commercial property'), ('AGRICULTURAL', 'Agricultural land / crops'), ('INFRASTRUCTURE', 'Public infrastructure'), ('LIVESTOCK', 'Livestock'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(help_text="The citizen's account of the damage.")),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField(blank=True)),
                ('district', models.CharField(blank=True, db_index=True, max_length=100)),
                ('location_source', models.CharField(choices=[('GPS', 'Browser GPS'), ('MANUAL', 'Manually entered'), ('EXIF', 'Photo metadata')], default='GPS', help_text='How the coordinates were obtained. Recorded for transparency.', max_length=20)),
                ('roof_collapsed', models.BooleanField(default=False, verbose_name='Roof completely collapsed')),
                ('people_trapped', models.BooleanField(default=False, verbose_name='People trapped')),
                ('exposed_live_wires', models.BooleanField(default=False, verbose_name='Exposed live wires')),
                ('standing_water', models.BooleanField(default=False, verbose_name='Standing water')),
                ('road_blocked', models.BooleanField(default=False, verbose_name='Road blocked')),
                ('major_structural_damage', models.BooleanField(default=False, verbose_name='Major structural damage')),
                ('wall_damage', models.BooleanField(default=False, verbose_name='Wall damage')),
                ('people_affected', models.PositiveSmallIntegerField(default=0, help_text='Number of people affected at this location.')),
                ('medical_assistance_needed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('TRIAGED', 'Triaged'), ('ASSIGNED', 'Assigned to officer'), ('INSPECTION_PENDING', 'Inspection in progress'), ('INSPECTED', 'Inspected'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('PAYOUT_PENDING', 'Payout pending'), ('PAYOUT_INITIATED', 'Payout initiated'), ('PAYOUT_COMPLETED', 'Payout completed'), ('REJECTED', 'Rejected'), ('NEEDS_REVIEW', 'Needs review'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', editable=False, help_text='Changed only through apply_transition(); never assigned directly.', max_length=25)),
                ('priority_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('triage_level', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', help_text='Client-generated unique key. If a phone retries a queued submission after a flaky reconnect, the duplicate is recognised and ignored.', max_length=64)),
                ('created_offline', models.BooleanField(default=False)),
                ('client_created_at', models.DateTimeField(blank=True, help_text='When the citizen actually filled the form, which may be days before it synced.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('citizen', models.ForeignKey(help_text='Owner of the report. PROTECT because relief history must not vanish.', on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=reports.validators.secure_upload_path, validators=[reports.validators.validate_image_upload])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exif_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('exif_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveSmallIntegerField(default=0)),
                ('height', models.PositiveSmallIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.disasterreport')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='disasterreport',
            index=models.Index(fields=['status', '-priority_score'], name='reports_dis_status_f8ba21_idx'),
        ),
        migrations.AddIndex(
            model_name='disasterreport',
            index=models.Index(fields=['district', 'status'], name='reports_dis_distric_078e91_idx'),
        ),
        migrations.AddIndex(
            model_name='disasterreport',
            index=models.Index(fields=['triage_level', '-created_at'], name='reports_dis_triage__d0fbd9_idx'),
        ),
        migrations.AddConstraint(
            model_name='disasterreport',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='report_latitude_within_range'),
        ),
        migrations.AddConstraint(
            model_name='disasterreport',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='report_longitude_within_range'),
        ),
        migrations.AddConstraint(
            model_name='disasterreport',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('citizen', 'idempotency_key'), name='unique_idempotency_key_per_citizen'),
        ),
    ]
