# Generated by Django 5.2.17 on 2026-08-15 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=60)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('entity_label', models.CharField(blank=True, help_text='Human-readable identifier, e.g. the report reference number.', max_length=120)),
                ('action', models.CharField(choices=[('REPORT_CREATED', 'Report created'), ('REPORT_SUBMITTED', 'Report submitted'), ('REPORT_UPDATED', 'Report updated'), ('REPORT_CANCELLED', 'Report cancelled'), ('EVIDENCE_UPLOADED', 'Evidence uploaded'), ('TRIAGE_COMPLETED', 'Triage completed'), ('OFFICER_ASSIGNED', 'Officer assigned'), ('ASSIGNMENT_ACCEPTED', 'Assignment accepted'), ('ASSIGNMENT_REASSIGNED', 'Assignment reassigned'), ('INSPECTION_STARTED', 'Inspection started'), ('INSPECTION_COMPLETED', 'Inspection completed'), ('OFFICER_SIGNED', 'Officer signed off'), ('COMPENSATION_CALCULATED', 'Compensation calculated'), ('ADMIN_APPROVED', 'Administrator approved'), ('ADMIN_REJECTED', 'Administrator rejected'), ('REVIEW_REQUESTED', 'Re-inspection requested'), ('PAYOUT_INITIATED', 'Payout initiated'), ('PAYOUT_COMPLETED', 'Payout completed'), ('USER_REGISTERED', 'User registered'), ('USER_LOGGED_IN', 'User logged in'), ('USER_LOGGED_OUT', 'User logged out'), ('OFFICER_CREATED', 'Officer account created'), ('OFFLINE_SYNC', 'Offline data synchronised')], db_index=True, max_length=40)),
                ('performed_by_username', models.CharField(blank=True, help_text='Snapshot of the username, preserved even if the account is removed.', max_length=150)),
                ('performed_by_role', models.CharField(blank=True, max_length=20)),
                ('previous_state', models.CharField(blank=True, max_length=40)),
                ('new_state', models.CharField(blank=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra context: scores, amounts, reasons. Must not contain secrets.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__0bff9a_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_c194db_idx')],
            },
        ),
    ]
