# Generated by Django 5.2.17 on 2026-09-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('REPORT_CREATED', 'Report created'), ('REPORT_SUBMITTED', 'Report submitted'), ('REPORT_UPDATED', 'Report updated'), ('REPORT_CANCELLED', 'Report cancelled'), ('EVIDENCE_UPLOADED', 'Evidence uploaded'), ('TRIAGE_COMPLETED', 'Triage completed'), ('OFFICER_ASSIGNED', 'Officer assigned'), ('ASSIGNMENT_ACCEPTED', 'Assignment accepted'), ('ASSIGNMENT_REASSIGNED', 'Assignment reassigned'), ('INSPECTION_STARTED', 'Inspection started'), ('INSPECTION_COMPLETED', 'Inspection completed'), ('OFFICER_SIGNED', 'Officer signed off'), ('COMPENSATION_CALCULATED', 'Compensation calculated'), ('ADMIN_APPROVED', 'Administrator approved'), ('ADMIN_REJECTED', 'Administrator rejected'), ('REVIEW_REQUESTED', 'Re-inspection requested'), ('PAYOUT_INITIATED', 'Payout initiated'), ('PAYOUT_COMPLETED', 'Payout completed'), ('USER_REGISTERED', 'User registered'), ('USER_LOGGED_IN', 'User logged in'), ('USER_LOGGED_OUT', 'User logged out'), ('OFFICER_CREATED', 'Officer account created'), ('OFFLINE_SYNC', 'Offline data synchronised'), ('SATELLITE_REQ', 'Satellite analysis requested'), ('SATELLITE_DONE', 'Satellite analysis completed'), ('DAMAGE_ASSESS', 'Damage assessment updated'), ('INTEGRITY_FLAGGED', 'Potential duplicate flagged'), ('INTEGRITY_REVIEWED', 'Potential duplicate reviewed')], db_index=True, max_length=40),
        ),
    ]
