# Generated by Django 5.2.17 on 2026-09-24 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0003_disasterreport_damage_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDamageAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_severity', models.CharField(blank=True, choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=8)),
                ('confidence_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('inferred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assessment', to='reports.reportphoto')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assessments', to='reports.disasterreport')),
            ],
            options={
                'ordering': ['photo_id'],
                'indexes': [models.Index(fields=['report', 'status'], name='damage_ai_a_report__f1e8b2_idx')],
            },
        ),
    ]
