# Generated by Django 5.2.17 on 2026-08-17 10:51

import django.db.models.deletion
import reports.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_label', models.CharField(blank=True, db_index=True, max_length=120)),
                ('pre_disaster_image', models.ImageField(upload_to=reports.validators.secure_upload_path, validators=[reports.validators.validate_image_upload])),
                ('post_disaster_image', models.ImageField(upload_to=reports.validators.secure_upload_path, validators=[reports.validators.validate_image_upload])),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('affected_area_hectares', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('region_geojson', models.JSONField(blank=True, default=dict, help_text='Optional GeoJSON polygon/multipolygon for the analysed area.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satellite_analyses', to='reports.disasterreport')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_satellite_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SatelliteDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_type', models.CharField(choices=[('FLOOD', 'Flooded area'), ('BUILDING_DAMAGE', 'Damaged building'), ('ROAD_DISRUPTION', 'Affected road')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('confidence', models.DecimalField(decimal_places=2, help_text='0-100 confidence from the model.', max_digits=5)),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('affected_area_hectares', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('geometry_geojson', models.JSONField(blank=True, default=dict, help_text='Optional GeoJSON polygon/line for the detection geometry.')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Model-specific evidence payload. Stored for traceability.')),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='satellite.satelliteanalysis')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='DamageAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_severity_score', models.PositiveSmallIntegerField(default=0)),
                ('photo_ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('satellite_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('field_verification_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_confidence', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('recommended_priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='LOW', max_length=10)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('is_field_verified', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='damage_assessment', to='reports.disasterreport')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_damage_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['recommended_priority', '-updated_at'], name='satellite_d_recomme_8ce7f8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='satelliteanalysis',
            index=models.Index(fields=['status', '-created_at'], name='satellite_s_status_df5133_idx'),
        ),
        migrations.AddIndex(
            model_name='satelliteanalysis',
            index=models.Index(fields=['zone_label', 'status'], name='satellite_s_zone_la_b2dd1c_idx'),
        ),
        migrations.AddIndex(
            model_name='satellitedetection',
            index=models.Index(fields=['detection_type', 'severity'], name='satellite_s_detecti_63a0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='satellitedetection',
            index=models.Index(fields=['-confidence'], name='satellite_s_confide_e4d06c_idx'),
        ),
    ]
