# Generated by Django 5.2.17 on 2026-08-15 04:27

import django.db.models.deletion
import django.utils.timezone
import reports.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('STARTED', 'Inspection started'), ('COMPLETED', 'Inspection completed'), ('SIGNED', 'Signed off by officer')], db_index=True, default='STARTED', max_length=12)),
                ('structural_damage', models.CharField(choices=[('NONE', 'No damage'), ('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('DESTROYED', 'Completely destroyed')], default='NONE', max_length=10)),
                ('roof_damage', models.CharField(choices=[('NONE', 'No damage'), ('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('DESTROYED', 'Completely destroyed')], default='NONE', max_length=10)),
                ('wall_damage', models.CharField(choices=[('NONE', 'No damage'), ('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('DESTROYED', 'Completely destroyed')], default='NONE', max_length=10)),
                ('foundation_damage', models.CharField(choices=[('NONE', 'No damage'), ('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('DESTROYED', 'Completely destroyed')], default='NONE', max_length=10)),
                ('electrical_damage', models.CharField(choices=[('NONE', 'No damage'), ('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('DESTROYED', 'Completely destroyed')], default='NONE', max_length=10)),
                ('water_damage', models.CharField(choices=[('NONE', 'No damage'), ('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('DESTROYED', 'Completely destroyed')], default='NONE', max_length=10)),
                ('household_damage', models.CharField(choices=[('NONE', 'No damage'), ('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('DESTROYED', 'Completely destroyed')], default='NONE', help_text='Furniture, appliances and other household contents.', max_length=10)),
                ('people_affected', models.PositiveSmallIntegerField(default=0, help_text="Verified count, which may differ from the citizen's estimate.")),
                ('is_habitable', models.BooleanField(default=True, help_text='Can the family safely remain in the property?')),
                ('requires_immediate_relief', models.BooleanField(default=False)),
                ('estimated_damage_value', models.DecimalField(decimal_places=2, default=0, help_text="Officer's own estimate in rupees. Advisory - the relief matrix decides the payment.", max_digits=12)),
                ('remarks', models.TextField(blank=True, help_text="Officer's field notes.")),
                ('inspection_latitude', models.DecimalField(blank=True, decimal_places=6, help_text="Officer's GPS position at sign-off, for on-site verification.", max_digits=9, null=True)),
                ('inspection_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_name', models.CharField(blank=True, help_text='Typed name recorded at sign-off. Not a cryptographic signature.', max_length=150)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('completed_offline', models.BooleanField(default=False)),
                ('client_completed_at', models.DateTimeField(blank=True, help_text='When the officer finished on site, before syncing.', null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='dispatch.assignment')),
                ('officer', models.ForeignKey(limit_choices_to={'role': 'FIELD_OFFICER'}, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='reports.disasterreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=reports.validators.secure_upload_path, validators=[reports.validators.validate_image_upload])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('damage_area', models.CharField(blank=True, help_text='Which part of the property this photo shows.', max_length=30)),
                ('captured_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('captured_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.inspection')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['officer', 'status'], name='inspections_officer_30a3d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='inspection',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('officer', 'idempotency_key'), name='unique_inspection_idempotency_key_per_officer'),
        ),
    ]
