# Generated by Django 5.2.17 on 2026-09-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_inspection_category_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='ai_verified_severity',
            field=models.CharField(blank=True, choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], help_text="Officer's separate verification of the preliminary AI severity assessment.", max_length=8, null=True),
        ),
    ]
