# Generated by Django 5.2.17 on 2026-08-15 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compensation', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVIEW_REQUESTED', 'Re-inspection requested')], db_index=True, max_length=20)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount authorised. Null for rejections and review requests.', max_digits=12, null=True)),
                ('reason', models.TextField(help_text='Mandatory. A relief decision must always carry a written justification.')),
                ('decided_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='compensation.compensationclaim')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='reports.disasterreport')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PAYOUT_PENDING', 'Payout pending'), ('PAYOUT_INITIATED', 'Payout initiated'), ('PAYOUT_COMPLETED', 'Payout completed'), ('PAYOUT_FAILED', 'Payout failed')], db_index=True, default='PAYOUT_PENDING', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Simulated transaction reference, e.g. PAY-2026-000012.', max_length=40, unique=True)),
                ('beneficiary_name', models.CharField(blank=True, max_length=150)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank transfer'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash counter')], default='BANK_TRANSFER', max_length=30)),
                ('is_simulated', models.BooleanField(default=True, help_text='True for this academic build. No real banking system is connected.')),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='approvals.approval')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts_initiated', to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='reports.disasterreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['decision', '-decided_at'], name='approvals_a_decisio_fb1a54_idx'),
        ),
    ]
